### ISSUE TITLE
Unsupport chinese ？

### ISSUE THREAD

**Issue by zakchan** [thierryc/Sketch-Find-And-Replace#13] opened 2016-06-06 07:17 UTC

**Comment by seandellis** [comment] 2017-05-18 06:24
Dupe of #7.

See https://github.com/mscodemonkey/Sketch-Find-And-Replace/issues/27 for image.

**Comment by thierryc** [comment] 2017-07-04 17:18
I close this one -> #7 
Helps wanted. 
Who can create a Sketch doc in chinese for us ?

**Closed by thierryc** 2017-07-04 17:18 UTC
Labels: duplicate, help wanted
