### ISSUE TITLE
Plugin hi-jacking non-matching symbol text

### ISSUE THREAD

**Issue by jack-ir** [thierryc/Sketch-Find-And-Replace#76] opened 2018-10-22 22:03 UTC
**Description**
Currently experiencing some interesting behaviour using find and replace where non-matching items are being replaced with a series of numbers and dashes in the override sections of symbols, but only the ones without overriding text.

**Steps to produce:**
1. Have a symbol with overrides, some filled with overrides some with just the default text
2. Use this plugin to find and replace a term that does not exist in the symbol

Expected behaviour:
Matches are replaced (working).

**Actual behaviour:**
Matches are replaced but also specific non-matches are replaced each with unique series of numbers and dashes (described above).

**Notes:**
Have attached a screen shot of post find and replace. I have the breadcrumb selected which is where the issue is manifesting. Notice that the last two sections of the breadcrumb are filled with those series of numbers. Also can be seen in the left panel.

**Specs:**
Sketch Version: 52.2
OS: 10.4 

p.s. appreciate your work, great plugin. Will provide more details if I can and is useful.

<img width="1552" alt="findreplace" src="https://user-images.githubusercontent.com/44354398/47322052-5aba3980-d6a2-11e8-9b7d-78d0b3067503.png">

**Comment by thierryc** [comment] 2018-10-22 22:15
Intersting. Strange bug. It should be an ID may be a sketch ID. 
Let me try to fix it. I keep you posted.

Thank you for this well documented issue.

**Comment by rodnem** [comment] 2018-11-12 10:30
Same here :/
Look at my little screencast where I blurred some area
https://cl.ly/8a049337fb5e

**Comment by thierryc** [comment] 2018-11-12 12:47
I saw. I can't reproduce it. Can you do a simple project (not confidential) with this issue?

**Comment by fjordaan** [comment] 2018-11-15 14:43
Also happened to me. Will have to stop using the plugin for now.

**Comment by thierryc** [comment] 2018-11-15 16:00
May I have your settings, your plug-ins list  and a sketch file to test ? 

It works on my computer. 

I suspect a plugin conflict. 

Test file: 
https://github.com/thierryc/Sketch-Find-And-Replace/tree/master/Test-doc

![find-and-replace](https://user-images.githubusercontent.com/197471/48564984-77264c00-e8c5-11e8-9d9f-609930ffa189.gif)

**Comment by jack-ir** [comment] 2018-11-16 01:10
Made up some redacted files so you could more closely inspect the issue.
[ReplaceTest.zip](https://github.com/thierryc/Sketch-Find-And-Replace/files/2587593/ReplaceTest.zip)

**Comment by jack-ir** [comment] 2018-11-16 01:35
I have all of those install but before do that you need to go back to my file and test it differently. The bug is with blank overrides only so with you putting in "Find Me" you're actually populating the override and making it so the bug will not reproduce. 

In my file specifically, you have to leave L4 and L5 blank (no override) to be able to reproduce the bug.

**Comment by fjordaan** [comment] 2018-11-16 11:17
I have the following plugins installed:
<img width="257" alt="image" src="https://user-images.githubusercontent.com/1419401/48618395-2a0fac00-e991-11e8-991f-282ef3b7ae1d.png">

**Comment by thierryc** [comment] 2018-11-16 15:06
works too 

https://www.dropbox.com/s/r0w9p51koih7z0r/find-and-replace2.mov?dl=0

**Comment by thierryc** [comment] 2018-11-16 15:15
![image](https://user-images.githubusercontent.com/197471/48629743-73a7c900-e988-11e8-9034-2fa2be6d8863.png)

**Comment by jack-ir** [comment] 2018-11-21 03:16
Should I try to remove Zeplin and see if it works?

**Comment by thierryc** [comment] 2018-11-21 13:43
@jack-ir thank you for the test.

**Comment by andaja** [comment] 2018-12-05 15:58
What is interesting in my case the bug happens only if you change a word (in blue "linked" text which is outside the artboard in the file attached). If you are changing the entire "linked" text it will not happen. It not only replaces the content of the symbols but also the linked styles of the symbol text and backgrounds. 
Here is my example. Initial file and the file after replace. 
https://www.dropbox.com/s/r6ks2uwwt9pdun2/test.sketch?dl=0
https://www.dropbox.com/s/u8vjq0fep98lvv8/test%20changed.sketch?dl=0

**Comment by thierryc** [comment] 2018-12-05 16:10
Thank you @andaja. I will explore your files.

**Comment by thierryc** [comment] 2019-01-09 23:06
Need a complete refactoring to use the JavaScript API.  https://developer.sketchapp.com/reference/api/#document

**Comment by thierryc** [comment] 2019-01-18 06:47
When I run replacing text, the text in the symbol got messed up with unknown series number #79

**Comment by thierryc** [comment] 2019-01-18 06:48
From @wangzhen0614 

"It seems the problem only happens if the text style in the symbol gets swapped (the new feature in sketch 52 where you can apply different style to each element in the symbol)"

**Comment by iconmaster** [comment] 2019-02-09 17:26
I just want to emphasize that this bug renders the plugin dangerous to use in a production environment. I screwed up a client design with it; managed to correct it with painstaking copy-paste from an older file.

**Comment by thierryc** [comment] 2019-02-09 18:55
command Z. works

**Comment by iconmaster** [comment] 2019-02-09 18:58
Sure, if you catch it quickly. Since the effect is unexpected, and can affect artboards out of view, it's extremely easy to miss.

**Comment by thierryc** [comment] 2019-02-09 19:40
V2 is in progress

**Comment by thierryc** [comment] 2019-02-09 19:41
Follow me on twitter to be posted. https://twitter.com/@Autre_planete

**Comment by thierryc** [comment] 2019-02-09 19:44
I take no responsibility for what you find and replace, or for any changes made unintentionally due to this software erroring. I do test it before I release it so the chances of bugs are minimised, but still, use wisely and completely at your own risk. Remember, cmd-z is your saviour.*

**Comment by thierryc** [comment] 2019-03-25 01:05
V2 is ready for beta tester.

**Comment by iconmaster** [comment] 2019-03-26 14:52
I really like the v2 UI!

So far it doesn't seem to find/replace anything.

**Comment by thierryc** [comment] 2019-03-26 15:35
@iconmaster Please test the last one. 
What is your sketch version? v2 is made for Sketch 53 and 54

On this repos you can find a sketch file to test it. Try to replace Occupation by WhatYouWant.

**Comment by thierryc** [comment] 2019-03-26 15:36
https://github.com/thierryc/Sketch-Find-And-Replace/archive/2.0.2.zip

**Comment by thierryc** [comment] 2019-03-26 15:36
The test document: https://github.com/thierryc/Sketch-Find-And-Replace/tree/master/Test-doc

**Comment by thierryc** [comment] 2019-03-26 15:38
Tips: Turn off regex. If you don't use it.

**Comment by iconmaster** [comment] 2019-03-26 15:43
I create a new, much simpler document and it did work as expected -- both on a text layer and a symbol override. So, probably no need to get hung up on my particular issue.

(I have Sketch 53.2 and used plugin v2.0.2. The test document can't be opened on my machine -- perhaps its a v54 document. Regex was off -- it was a find and replace on the whole page.)

**Comment by thierryc** [comment] 2019-03-26 15:46
v54 document. Yes, It is. 
Please send me your doc for a test. Thank you for your help.

**Comment by thierryc** [comment] 2019-03-26 15:51
I have create a new v53 test document.
https://github.com/thierryc/Sketch-Find-And-Replace/tree/master/Test-doc

**Comment by thierryc** [comment] 2019-03-26 17:08
@iconmaster

https://github.com/thierryc/Sketch-Find-And-Replace/releases/tag/2.0.3

**Comment by iconmaster** [comment] 2019-03-26 17:59
@thierryc Yes! Seeing some results now. I'll keep testing.

**Comment by thierryc** [comment] 2019-03-26 18:17
@iconmaster Thank you 

v2.0.4

<img width="462" alt="image" src="https://user-images.githubusercontent.com/197471/55022862-df9edb80-4fd1-11e9-9792-e496a90f4416.png">

**Comment by thierryc** [comment] 2019-04-01 11:19
2.0.7 is out

**Comment by iconmaster** [comment] 2019-04-01 14:25
This has been working well!

**Comment by iconmaster** [comment] 2019-04-03 00:36
After several successful uses, the plugin is now crashing Sketch on each activation. I tried trashing the plugin preferences and reinstalling the plugin. Is there another file I should scrap?

**Comment by iconmaster** [comment] 2019-04-03 02:11
v2 was crashing Sketch 53.2 for a bit but is working fine following a reboot. It's nice to have this back.

**Comment by thierryc** [comment] 2019-04-03 11:31
Do you try to use a special chars before it crash? like \

**Comment by iconmaster** [comment] 2019-04-03 17:07
That might have been it. I just tried again with a grep replace and it actually seemed to work as expected, but Sketch crashed almost immediately afterward. Now I'm back to crash on plugin open. 

I wonder why the reboot fixed it.. have to assume it's a corrupted preference or cache file that gets wiped on restart.

**Comment by thierryc** [comment] 2019-04-03 17:13
Yes. Preference and last find saved can crash sketch. 
I will try to fix this.

**Comment by iconmaster** [comment] 2019-04-16 14:48
Recommend to close this issue. Latest versions do not exhibit any of the random replacement behavior.

**Comment by thierryc** [comment] 2019-04-16 16:33
Latest versions do not exhibit any of the random replacement behavior.

**Closed by thierryc** 2019-04-16 16:33 UTC
Labels: bug, help wanted
