### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by mischugo** [thierryc/Sketch-Find-And-Replace#24] opened 2017-03-15 13:33 UTC
Any chance to have the option for "find only", placed in a list?
And then from there, a link to the appropriate layer :-)

Best!!!

**Comment by rodnem** [comment] 2017-03-21 14:50
Or simply a selection of the found layers on the same page

**Comment by seandellis** [comment] 2017-05-18 06:04
Duplicate of #18

**Comment by thierryc** [comment] 2017-07-04 17:01
Assigned to me in #18. I close this issue. Thank you @mischugo

**Closed** 2017-07-04 17:03 UTC
